//! tauri-specta pilot (#589): a *separate*, minimal Specta [`Builder`] scoped
//! to the `orders` module's single command, used only to drive the TypeScript
//! export. This does **not** replace the real `tauri::generate_handler!` list
//! in [`crate::run`] — the 300+ existing commands aren't specta-annotated, so
//! migrating the whole `invoke_handler` isn't in scope for this spike. If the
//! pilot expands to more modules, add their commands to `collect_commands!`
//! here and derive `specta::Type` on their DTOs; nothing else changes.

use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::Builder;

/// Path is relative to `src-tauri/` (Cargo's working directory for both
/// `cargo test` and `cargo run`).
const ORDERS_BINDINGS_PATH: &str = "../src/lib/api/generated/orders.ts";

fn builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(crate::modules::orders::commands::specta_commands())
}

/// Regenerates `src/lib/api/generated/orders.ts` (raw, un-prettified — this
/// crate deliberately stays Node-independent so `cargo test` alone works in
/// the Rust CI job). `npm run generate:bindings`/`npm run build` chain a
/// `prettier --write` afterwards to match the committed, repo-styled file;
/// running this test directly leaves the file prettier-dirty until that runs.
pub fn export_orders_bindings() {
    builder()
        .export(
            Typescript::default()
                // ESI ids fit well inside f64's 53-bit safe integer range in
                // practice; matches the `number` the hand-written mirror this
                // replaces already used for every i64 field.
                .bigint(BigIntExportBehavior::Number)
                .header(
                    "// @ts-nocheck — tauri-specta always emits a Channel import and a\n\
                     // makeEvents() helper even when a module has no events (specta-rs/tauri-specta#198),\n\
                     // which trips this repo's noUnusedLocals under tsc. AUTO-GENERATED by\n\
                     // tauri-specta (see src-tauri/src/bindings.rs) — do not hand-edit.\n",
                ),
            ORDERS_BINDINGS_PATH,
        )
        .expect("failed to export orders TS bindings");
}

/// Gated behind the `export-bindings` feature so a plain `cargo test` (the
/// documented standard command) stays side-effect-free with respect to git
/// state — the always-on version rewrote the committed file un-prettified on
/// every suite run, leaving the tree dirty during unrelated Rust work.
#[cfg(all(test, feature = "export-bindings"))]
mod tests {
    use super::export_orders_bindings;

    /// Regenerates the committed bindings file. CI's "Regenerate bindings"
    /// step runs this via `npm run generate:bindings` (`cargo test --features
    /// export-bindings export_orders_bindings --quiet` + prettier); run the
    /// same script by hand after touching `OrderRow` or `orders_list`'s
    /// signature and check in the diff — CI's drift check fails otherwise.
    /// Deliberately NOT part of `npm run build`: release builds consume the
    /// committed file (the cargo test binary crashes on the Windows runner
    /// under tauri-action, and the drift gate already guarantees freshness).
    #[test]
    fn export_orders_bindings_regenerates_the_committed_file() {
        export_orders_bindings();
    }
}
