//! tauri-specta pilot (#589), extended by #836: separate, minimal Specta
//! [`Builder`]s scoped to a handful of modules' commands, used only to drive
//! the TypeScript export. This does **not** replace the real
//! `tauri::generate_handler!` list in [`crate::run`] — the 300+ existing
//! commands aren't all specta-annotated, so migrating the whole
//! `invoke_handler` isn't in scope. To add a module: annotate its commands
//! with `#[specta::specta]`, derive `specta::Type` on their DTOs, add a
//! `builder()`/`export_*_bindings()` pair below (copy an existing one), wire
//! it into `npm run generate:bindings` (package.json) and the `tests` module
//! here, and register it in the migration-order list below.
//!
//! Every command surfaced here must return `Result<T, crate::model::AppError>`
//! (or a non-`Result` value) — [`fix_as_any`] assumes the error branch is
//! always `AppError` when it rewrites tauri-specta's generated `as any` cast.
//!
//! Migration order (#836; done modules first, remaining ~290 commands are
//! still hand-typed via `src/lib/api/*.ts` wrappers calling `invoke` directly):
//!   1. `orders` — done (#589 pilot).
//!   2. `market`, `auth` (esi), `production` — done (#836).
//!   3. Remaining, in rough call-site-count order: `trading`, `assets`,
//!      `industry`, `character`, `route`, `fitting`, `shopping`, `intel`,
//!      `daytrading`, `contracts`, `accounting`, `reprocessing`, `lpstore`,
//!      `wormholes`, `pochven`, `pi`, `localintel`, `pvp`, `notifications`,
//!      `dpsmeter`, `scripts`, `appraisal`, `logs`, `feedback`, `plugins`,
//!      `mcp`, `sde`, `info` — not yet started; each should get its own
//!      `builder()`/`export_*_bindings()` pair plus a hand-written
//!      `src/lib/api/<module>.ts` wrapper deleted in favor of the generated
//!      file, per the `orders`/`market`/`auth`/`production` pattern.

use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::Builder;

fn orders_builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(crate::modules::orders::commands::specta_commands())
}

fn market_builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(crate::market::commands::specta_commands())
}

fn auth_builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(crate::esi::commands::specta_commands())
}

fn production_builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(crate::modules::production::commands::specta_commands())
}

/// ESI ids fit well inside f64's 53-bit safe integer range in practice, and
/// every generated module's header disables `noUnusedLocals`-tripping
/// tauri-specta boilerplate (see [`export_bindings`]'s doc comment).
fn language() -> Typescript {
    Typescript::default()
        .bigint(BigIntExportBehavior::Number)
        .header(
            "// @ts-nocheck — tauri-specta always emits a Channel import and a\n\
             // makeEvents() helper even when a module has no events (specta-rs/tauri-specta#198),\n\
             // which trips this repo's noUnusedLocals under tsc. AUTO-GENERATED by\n\
             // tauri-specta (see src-tauri/src/bindings.rs) — do not hand-edit.\n",
        )
}

/// tauri-specta's TypeScript exporter hardcodes an ` as any` cast onto the
/// error branch of every generated command's catch clause (`tauri-specta`
/// v2's `js_ts::return_as_result_tuple`, unconditionally for TS — there is
/// no builder option to opt out; the emitted source is `error: e  as any`,
/// two spaces, since the template already has one before the conditional
/// `" as any"` fragment). Every command surfaced through this module returns
/// `Result<T, AppError>`, so the cast is always narrowable to the real error
/// type: rewrite it post-render rather than forking the crate. This
/// deliberately does **not** touch the unrelated `(() => {}) as any` inside
/// tauri-specta's `__makeEvents__` helper (specta-rs/tauri-specta#198) —
/// that's inert library boilerplate under the file's `@ts-nocheck` header,
/// not a per-command error type we can narrow.
fn fix_as_any(rendered: String) -> String {
    rendered.replace(" as any };", " as AppError };")
}

/// Regenerates a module's generated bindings file (raw, un-prettified — this
/// crate deliberately stays Node-independent so `cargo test` alone works in
/// the Rust CI job). `npm run generate:bindings`/`npm run build` chain a
/// `prettier --write` afterwards to match the committed, repo-styled file.
///
/// This also runs on every `tauri dev` debug launch (see [`crate::run`]), so
/// it must be a no-op when nothing actually changed (#810): the raw output
/// here and the prettier-formatted committed file always differ *textually*
/// (indentation, line breaks) even when the module's commands/DTOs are
/// identical, and blindly overwriting on every launch turned that whitespace
/// gap into permanent working-tree drift. So the export is rendered to a
/// string first and compared against the committed file with insignificant
/// whitespace stripped from both sides — the file on disk (and its mtime) is
/// left alone unless the comparison finds a real signature change, and in
/// that case the raw (unformatted) output is written, exactly as before, for
/// `npm run generate:bindings`'s trailing `prettier --write` to tidy up.
fn export_bindings(builder: Builder, path: &str) {
    let rendered = fix_as_any(
        builder
            .export_str(&language())
            .expect("failed to render TS bindings"),
    );
    let committed = std::fs::read_to_string(path).unwrap_or_default();
    if normalize_whitespace(&committed) == normalize_whitespace(&rendered) {
        return; // Same signature as committed, just reformatted — leave the file alone.
    }
    if let Some(dir) = std::path::Path::new(path).parent() {
        std::fs::create_dir_all(dir).expect("failed to create bindings directory");
    }
    std::fs::write(path, rendered).expect("failed to write TS bindings");
}

/// Path is relative to `src-tauri/` (Cargo's working directory for both
/// `cargo test` and `cargo run`).
pub fn export_orders_bindings() {
    export_bindings(orders_builder(), "../src/lib/api/generated/orders.ts");
}

pub fn export_market_bindings() {
    export_bindings(market_builder(), "../src/lib/api/generated/market.ts");
}

pub fn export_auth_bindings() {
    export_bindings(auth_builder(), "../src/lib/api/generated/auth.ts");
}

pub fn export_production_bindings() {
    export_bindings(
        production_builder(),
        "../src/lib/api/generated/production.ts",
    );
}

/// Collapse every run of whitespace to a single space, so two renderings of
/// the same TypeScript that differ only in indentation/line breaks (raw
/// tauri-specta output vs. the prettier-formatted committed file) compare
/// equal. TypeScript has no whitespace-significant syntax this could
/// misfire on (no Python-style indentation, no heredocs in generated code).
fn normalize_whitespace(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Gated behind the `export-bindings` feature so a plain `cargo test` (the
/// documented standard command) stays side-effect-free with respect to git
/// state — the always-on version rewrote the committed file un-prettified on
/// every suite run, leaving the tree dirty during unrelated Rust work.
#[cfg(all(test, feature = "export-bindings"))]
mod tests {
    use super::{
        export_auth_bindings, export_market_bindings, export_orders_bindings,
        export_production_bindings,
    };

    /// Regenerates the committed bindings files. CI's "Regenerate bindings"
    /// step runs this via `npm run generate:bindings` (`cargo test --features
    /// export-bindings export_bindings_regenerate --quiet` + prettier); run
    /// the same script by hand after touching a covered module's commands or
    /// DTOs and check in the diff — CI's drift check fails otherwise.
    /// Deliberately NOT part of `npm run build`: release builds consume the
    /// committed files (the cargo test binary crashes on the Windows runner
    /// under tauri-action, and the drift gate already guarantees freshness).
    #[test]
    fn export_bindings_regenerate_the_committed_files() {
        export_orders_bindings();
        export_market_bindings();
        export_auth_bindings();
        export_production_bindings();
    }
}
