//! tauri-specta pilot (#589): a *separate*, minimal Specta [`Builder`] scoped
//! to the `orders` module's single command, used only to drive the TypeScript
//! export. This does **not** replace the real `tauri::generate_handler!` list
//! in [`crate::run`] — the 300+ existing commands aren't specta-annotated, so
//! migrating the whole `invoke_handler` isn't in scope for this spike. If the
//! pilot expands to more modules, add their commands to `collect_commands!`
//! here and derive `specta::Type` on their DTOs; nothing else changes.

use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::Builder;

/// Path is relative to `src-tauri/` (Cargo's working directory for both
/// `cargo test` and `cargo run`).
const ORDERS_BINDINGS_PATH: &str = "../src/lib/api/generated/orders.ts";

fn builder() -> Builder {
    Builder::<tauri::Wry>::new().commands(crate::modules::orders::commands::specta_commands())
}

/// Regenerates `src/lib/api/generated/orders.ts` (raw, un-prettified — this
/// crate deliberately stays Node-independent so `cargo test` alone works in
/// the Rust CI job). `npm run generate:bindings`/`npm run build` chain a
/// `prettier --write` afterwards to match the committed, repo-styled file.
///
/// This also runs on every `tauri dev` debug launch (see [`crate::run`]), so
/// it must be a no-op when nothing actually changed (#810): the raw output
/// here and the prettier-formatted committed file always differ *textually*
/// (indentation, line breaks) even when `OrderRow`/`orders_list`'s shape is
/// identical, and blindly overwriting on every launch turned that whitespace
/// gap into permanent working-tree drift. So the export is rendered to a
/// string first and compared against the committed file with insignificant
/// whitespace stripped from both sides — the file on disk (and its mtime) is
/// left alone unless the comparison finds a real signature change, and in
/// that case the raw (unformatted) output is written, exactly as before, for
/// `npm run generate:bindings`'s trailing `prettier --write` to tidy up.
pub fn export_orders_bindings() {
    let language = Typescript::default()
        // ESI ids fit well inside f64's 53-bit safe integer range in
        // practice; matches the `number` the hand-written mirror this
        // replaces already used for every i64 field.
        .bigint(BigIntExportBehavior::Number)
        .header(
            "// @ts-nocheck — tauri-specta always emits a Channel import and a\n\
             // makeEvents() helper even when a module has no events (specta-rs/tauri-specta#198),\n\
             // which trips this repo's noUnusedLocals under tsc. AUTO-GENERATED by\n\
             // tauri-specta (see src-tauri/src/bindings.rs) — do not hand-edit.\n",
        );
    let rendered = builder()
        .export_str(&language)
        .expect("failed to render orders TS bindings");
    let committed = std::fs::read_to_string(ORDERS_BINDINGS_PATH).unwrap_or_default();
    if normalize_whitespace(&committed) == normalize_whitespace(&rendered) {
        return; // Same signature as committed, just reformatted — leave the file alone.
    }
    if let Some(dir) = std::path::Path::new(ORDERS_BINDINGS_PATH).parent() {
        std::fs::create_dir_all(dir).expect("failed to create orders bindings directory");
    }
    std::fs::write(ORDERS_BINDINGS_PATH, rendered).expect("failed to write orders TS bindings");
}

/// Collapse every run of whitespace to a single space, so two renderings of
/// the same TypeScript that differ only in indentation/line breaks (raw
/// tauri-specta output vs. the prettier-formatted committed file) compare
/// equal. TypeScript has no whitespace-significant syntax this could
/// misfire on (no Python-style indentation, no heredocs in generated code).
fn normalize_whitespace(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Gated behind the `export-bindings` feature so a plain `cargo test` (the
/// documented standard command) stays side-effect-free with respect to git
/// state — the always-on version rewrote the committed file un-prettified on
/// every suite run, leaving the tree dirty during unrelated Rust work.
#[cfg(all(test, feature = "export-bindings"))]
mod tests {
    use super::export_orders_bindings;

    /// Regenerates the committed bindings file. CI's "Regenerate bindings"
    /// step runs this via `npm run generate:bindings` (`cargo test --features
    /// export-bindings export_orders_bindings --quiet` + prettier); run the
    /// same script by hand after touching `OrderRow` or `orders_list`'s
    /// signature and check in the diff — CI's drift check fails otherwise.
    /// Deliberately NOT part of `npm run build`: release builds consume the
    /// committed file (the cargo test binary crashes on the Windows runner
    /// under tauri-action, and the drift gate already guarantees freshness).
    #[test]
    fn export_orders_bindings_regenerates_the_committed_file() {
        export_orders_bindings();
    }
}
